In [38]:
import pandas as pd
import sys
import os
import numpy as np

In [39]:
wdir = r'Z:\Data-Expansion\users\lelise\projects\Carolinas_SFINCS\Chapter3_SyntheticTCs\05_ANALYSIS\aep'
os.chdir(wdir)

csvfiles = [f for f in os.listdir(wdir) if f.endswith('.csv')]
print(csvfiles)

['canesm_ssp585_rp_flood_stats_sbgRes5m_hmin0.05m.csv', 'ncep_rp_flood_stats_sbgRes5m_hmin0.05m.csv']


In [40]:
# Present AEP
df1 = pd.read_csv(csvfiles[1], index_col=0)
df1.index = df1.index.str.replace(' ', '', regex=False)
df1 = df1[~df1.index.duplicated(keep='last')]
df1.index = df1.index.str.split('_', expand=True)
df1.index.names = ['rp','basin','attr']
df1.reset_index(inplace=True)
mapping = {'attr1': 'Coastal', 'attr2': 'Compound', 'attr3': 'Runoff'}
df1['attr'] = df1['attr'].map(lambda x: mapping.get(x, 'Total'))

df_hist = df1
df_hist

rp        basin      attr        count   mean    std   min    50%  \
0     RP10       Domain     Total  155108156.0  0.518  0.558  0.05  0.349   
1     RP10       Domain   Coastal   92692771.0  0.678  0.603  0.05  0.559   
2     RP10       Domain  Compound   14365771.0  0.445  0.613  0.05  0.272   
3     RP10       Domain    Runoff   48020667.0  0.232  0.419  0.05  0.129   
4     RP10      Pamlico     Total   62193292.0  0.606  0.500  0.05  0.489   
..     ...          ...       ...          ...    ...    ...   ...    ...   
115  RP250     CapeFear    Runoff   73007556.0  0.719  0.809  0.05  0.387   
116  RP250  LowerPeeDee     Total  297932086.0  0.780  0.689  0.05  0.523   
117  RP250  LowerPeeDee   Coastal   11766324.0  1.961  1.210  0.05  1.801   
118  RP250  LowerPeeDee  Compound   39162325.0  0.513  0.511  0.05  0.322   
119  RP250  LowerPeeDee    Runoff  247003437.0  0.766  0.638  0.05  0.544   

       90%    95%     max  Area_sqkm  
0    1.136  1.443  10.000   3877.704  
1    1.321  1.595  10.000   2317.319  
2    0.890  1.162  10.000    359.144  
3    0.402  0.655  10.000   1200.517  
4    1.304  1.542  10.000   1554.832  
..     ...    ...     ...        ...  
115  1.851  2.388  10.000   1825.189  
116  1.737  2.156  10.000   7448.302  
117  3.284  3.969  10.000    294.158  
118  1.223  1.616   9.999    979.058  
119  1.680  2.035  10.000   6175.086  

[120 rows x 12 columns]

In [41]:
# Future AEP
df1 = pd.read_csv(csvfiles[0], index_col=0)
df1.index = df1.index.str.replace(' ', '', regex=False)
df1 = df1[~df1.index.duplicated(keep='last')]
df1.index = df1.index.str.split('_', expand=True)
df1.index.names = ['rp','basin','attr']
df1.reset_index(inplace=True)
mapping = {'attr1': 'Coastal', 'attr2': 'Compound', 'attr3': 'Runoff'}
df1['attr'] = df1['attr'].map(lambda x: mapping.get(x, 'Total'))

df_fut = df1
df_fut

rp        basin      attr        count   mean    std   min    50%  \
0     RP10       Domain     Total  341919668.0  0.493  0.473  0.05  0.339   
1     RP10       Domain   Coastal   78458159.0  0.729  0.604  0.05  0.626   
2     RP10       Domain  Compound   36792977.0  0.653  0.566  0.05  0.479   
3     RP10       Domain    Runoff  226656647.0  0.385  0.431  0.05  0.247   
4     RP10      Pamlico     Total   88018638.0  0.577  0.507  0.05  0.446   
..     ...          ...       ...          ...    ...    ...   ...    ...   
115  RP250     CapeFear    Runoff  110215572.0  1.156  1.223  0.05  0.685   
116  RP250  LowerPeeDee     Total  352780172.0  1.097  0.913  0.05  0.677   
117  RP250  LowerPeeDee   Coastal   10627566.0  2.072  1.227  0.05  1.990   
118  RP250  LowerPeeDee  Compound   61418379.0  0.777  0.841  0.05  0.394   
119  RP250  LowerPeeDee    Runoff  280734227.0  1.131  0.995  0.05  0.748   

       90%    95%     max  Area_sqkm  
0    1.076  1.436  10.000   8547.992  
1    1.321  1.680  10.000   1961.454  
2    1.420  1.592   9.999    919.824  
3    0.813  1.179  10.000   5666.416  
4    1.279  1.546   9.999   2200.466  
..     ...    ...     ...        ...  
115  2.940  3.897  10.000   2755.389  
116  2.670  3.360  10.000   8819.504  
117  3.324  4.023  10.000    265.689  
118  2.147  2.764   9.997   1535.459  
119  2.713  3.468  10.000   7018.356  

[120 rows x 12 columns]

In [58]:
domain_hist = df_hist[df_hist['basin'] == 'Domain']
domain_hist.reset_index(inplace=True, drop=True)
domain_hist

rp   basin      attr        count   mean    std   min    50%    90%  \
0    RP10  Domain     Total  155108156.0  0.518  0.558  0.05  0.349  1.136   
1    RP10  Domain   Coastal   92692771.0  0.678  0.603  0.05  0.559  1.321   
2    RP10  Domain  Compound   14365771.0  0.445  0.613  0.05  0.272  0.890   
3    RP10  Domain    Runoff   48020667.0  0.232  0.419  0.05  0.129  0.402   
4    RP25  Domain     Total  311044623.0  0.519  0.502  0.05  0.349  1.155   
5    RP25  Domain   Coastal  107176443.0  0.822  0.640  0.05  0.724  1.493   
6    RP25  Domain  Compound   22476505.0  0.526  0.568  0.05  0.329  1.145   
7    RP25  Domain    Runoff  181378648.0  0.339  0.401  0.05  0.225  0.697   
8    RP50  Domain     Total  429061791.0  0.586  0.510  0.05  0.410  1.308   
9    RP50  Domain   Coastal  113625792.0  0.941  0.704  0.05  0.855  1.662   
10   RP50  Domain  Compound   38234154.0  0.623  0.599  0.05  0.395  1.474   
11   RP50  Domain    Runoff  277189528.0  0.435  0.454  0.05  0.282  0.941   
12  RP100  Domain     Total  540429968.0  0.679  0.528  0.05  0.472  1.516   
13  RP100  Domain   Coastal  115234951.0  1.078  0.767  0.05  0.996  1.901   
14  RP100  Domain  Compound   66518622.0  0.695  0.648  0.05  0.442  1.612   
15  RP100  Domain    Runoff  358665114.0  0.548  0.523  0.05  0.342  1.263   
16  RP250  Domain     Total  652435183.0  0.800  0.629  0.05  0.541  1.816   
17  RP250  Domain   Coastal  116633335.0  1.254  0.833  0.05  1.202  2.147   
18  RP250  Domain  Compound  117889670.0  0.716  0.735  0.05  0.425  1.779   
19  RP250  Domain    Runoff  417900781.0  0.697  0.633  0.05  0.423  1.650   

      95%     max  Area_sqkm  
0   1.443  10.000   3877.704  
1   1.595  10.000   2317.319  
2   1.162  10.000    359.144  
3   0.655  10.000   1200.517  
4   1.457  10.000   7776.116  
5   1.838  10.000   2679.411  
6   1.428   9.998    561.913  
7   0.955  10.000   4534.466  
8   1.622  10.000  10726.545  
9   2.013  10.000   2840.645  
10  1.679   9.999    955.854  
11  1.238  10.000   6929.738  
12  1.856  10.000  13510.749  
13  2.250  10.000   2880.874  
14  1.853  10.000   1662.966  
15  1.583  10.000   8966.628  
16  2.204  10.000  16310.880  
17  2.526  10.000   2915.833  
18  2.198  10.000   2947.242  
19  2.052  10.000  10447.520

In [59]:
domain_fut = df_fut[df_fut['basin'] == 'Domain']
domain_fut.reset_index(inplace=True, drop=True)
domain_fut

rp   basin      attr        count   mean    std   min    50%    90%  \
0    RP10  Domain     Total  341919668.0  0.493  0.473  0.05  0.339  1.076   
1    RP10  Domain   Coastal   78458159.0  0.729  0.604  0.05  0.626  1.321   
2    RP10  Domain  Compound   36792977.0  0.653  0.566  0.05  0.479  1.420   
3    RP10  Domain    Runoff  226656647.0  0.385  0.431  0.05  0.247  0.813   
4    RP25  Domain     Total  523222321.0  0.643  0.537  0.05  0.440  1.421   
5    RP25  Domain   Coastal   67230513.0  0.895  0.630  0.05  0.813  1.551   
6    RP25  Domain  Compound   82033883.0  0.840  0.699  0.05  0.665  1.698   
7    RP25  Domain    Runoff  373946534.0  0.555  0.563  0.05  0.332  1.260   
8    RP50  Domain     Total  636925810.0  0.761  0.650  0.05  0.509  1.724   
9    RP50  Domain   Coastal   63794041.0  1.025  0.690  0.05  0.977  1.690   
10   RP50  Domain  Compound  126759047.0  0.887  0.773  0.05  0.663  1.903   
11   RP50  Domain    Runoff  446361580.0  0.687  0.674  0.05  0.397  1.648   
12  RP100  Domain     Total  737375792.0  0.892  0.694  0.05  0.579  2.069   
13  RP100  Domain   Coastal   75711577.0  1.252  0.817  0.05  1.208  2.036   
14  RP100  Domain  Compound  180509057.0  0.949  0.895  0.05  0.628  2.185   
15  RP100  Domain    Runoff  481144192.0  0.814  0.775  0.05  0.460  2.008   
16  RP250  Domain     Total  853571558.0  1.078  0.809  0.05  0.704  2.531   
17  RP250  Domain   Coastal   67740836.0  1.441  0.870  0.05  1.401  2.420   
18  RP250  Domain  Compound  250860605.0  0.963  0.896  0.05  0.605  2.246   
19  RP250  Domain    Runoff  534959168.0  1.086  0.990  0.05  0.657  2.712   

      95%     max  Area_sqkm  
0   1.436  10.000   8547.992  
1   1.680  10.000   1961.454  
2   1.592   9.999    919.824  
3   1.179  10.000   5666.416  
4   1.806  10.000  13080.558  
5   1.925  10.000   1680.763  
6   2.016  10.000   2050.847  
7   1.690  10.000   9348.663  
8   2.171  10.000  15923.145  
9   1.967  10.000   1594.851  
10  2.346  10.000   3168.976  
11  2.136  10.000  11159.040  
12  2.663  10.000  18434.395  
13  2.485  10.000   1892.789  
14  2.701  10.000   4512.726  
15  2.672  10.000  12028.605  
16  3.269  10.000  21339.289  
17  2.899  10.000   1693.521  
18  2.869  10.000   6271.515  
19  3.503  10.000  13373.979

In [57]:
numeric_cols = domain_hist.select_dtypes(include='number').columns

diff = (domain_fut[numeric_cols] - domain_hist[numeric_cols])
diff['sf_area'] = 1 + sf['Area_sqkm'].div(domain_hist['Area_sqkm'])
diff = np.round(diff,4)
diff[['rp','basin', 'attr']] = domain_hist[['rp','basin', 'attr']]
diff

count   mean    std  min    50%    90%    95%    max  Area_sqkm  \
0   186811512.0 -0.025 -0.085  0.0 -0.010 -0.060 -0.007  0.000   4670.288   
1   -14234612.0  0.051  0.001  0.0  0.067  0.000  0.085  0.000   -355.865   
2    22427206.0  0.208 -0.047  0.0  0.207  0.530  0.430 -0.001    560.680   
3   178635980.0  0.153  0.012  0.0  0.118  0.411  0.524  0.000   4465.899   
4   212177698.0  0.124  0.035  0.0  0.091  0.266  0.349  0.000   5304.442   
5   -39945930.0  0.073 -0.010  0.0  0.089  0.058  0.087  0.000   -998.648   
6    59557378.0  0.314  0.131  0.0  0.336  0.553  0.588  0.002   1488.934   
7   192567886.0  0.216  0.162  0.0  0.107  0.563  0.735  0.000   4814.197   
8   207864019.0  0.175  0.140  0.0  0.099  0.416  0.549  0.000   5196.600   
9   -49831751.0  0.084 -0.014  0.0  0.122  0.028 -0.046  0.000  -1245.794   
10   88524893.0  0.264  0.174  0.0  0.268  0.429  0.667  0.001   2213.122   
11  169172052.0  0.252  0.220  0.0  0.115  0.707  0.898  0.000   4229.302   
12  196945824.0  0.213  0.166  0.0  0.107  0.553  0.807  0.000   4923.646   
13  -39523374.0  0.174  0.050  0.0  0.212  0.135  0.235  0.000   -988.085   
14  113990435.0  0.254  0.247  0.0  0.186  0.573  0.848  0.000   2849.760   
15  122479078.0  0.266  0.252  0.0  0.118  0.745  1.089  0.000   3061.977   
16  201136375.0  0.278  0.180  0.0  0.163  0.715  1.065  0.000   5028.409   
17  -48892499.0  0.187  0.037  0.0  0.199  0.273  0.373  0.000  -1222.312   
18  132970935.0  0.247  0.161  0.0  0.180  0.467  0.671  0.000   3324.273   
19  117058387.0  0.389  0.357  0.0  0.234  1.062  1.451  0.000   2926.459   

    sf_area     rp   basin      attr  
0    2.2044   RP10  Domain     Total  
1    0.8464   RP10  Domain   Coastal  
2    2.5612   RP10  Domain  Compound  
3    4.7200   RP10  Domain    Runoff  
4    1.6821   RP25  Domain     Total  
5    0.6273   RP25  Domain   Coastal  
6    3.6498   RP25  Domain  Compound  
7    2.0617   RP25  Domain    Runoff  
8    1.4845   RP50  Domain     Total  
9    0.5614   RP50  Domain   Coastal  
10   3.3153   RP50  Domain  Compound  
11   1.6103   RP50  Domain    Runoff  
12   1.3644  RP100  Domain     Total  
13   0.6570  RP100  Domain   Coastal  
14   2.7137  RP100  Domain  Compound  
15   1.3415  RP100  Domain    Runoff  
16   1.3083  RP250  Domain     Total  
17   0.5808  RP250  Domain   Coastal  
18   2.1279  RP250  Domain  Compound  
19   1.2801  RP250  Domain    Runoff

In [95]:
df = domain_fut[['Area_sqkm',	'rp','attr']]
for rp in np.unique(diff['rp'].values):
    data1 = df[df['rp'] == rp]
    data = data1.drop('rp', axis=1)
    data.set_index('attr', inplace=True, drop=True)
    data = data.T[['Coastal', 'Compound','Runoff']]
    data.reset_index(drop=True, inplace=True)
    cont = data.sum(axis=1)
    r = data.to_numpy() / cont.item()
    print(rp)
    print(np.round(r*100,3))
    

RP10
[[22.947 10.761 66.292]]
RP100
[[10.268 24.48  65.252]]
RP25
[[12.85  15.679 71.471]]
RP250
[[ 7.936 29.39  62.674]]
RP50
[[10.016 19.902 70.082]]


In [96]:
df = domain_hist[['Area_sqkm',	'rp','attr']]
for rp in np.unique(diff['rp'].values):
    data1 = df[df['rp'] == rp]
    data = data1.drop('rp', axis=1)
    data.set_index('attr', inplace=True, drop=True)
    data = data.T[['Coastal', 'Compound','Runoff']]
    data.reset_index(drop=True, inplace=True)
    cont = data.sum(axis=1)
    r = data.to_numpy() / cont.item()
    print(rp)
    print(np.round(r*100,3))

RP10
[[59.771  9.263 30.965]]
RP100
[[21.323 12.309 66.368]]
RP25
[[34.458  7.226 58.315]]
RP250
[[17.877 18.069 64.054]]
RP50
[[26.483  8.911 64.605]]
